name: msvc-test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: msvc-test
    runs-on: windows-latest

    steps:
     
    - name: checkout
      uses: actions/checkout@v4.1.7

    - name: setup dependencies
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild
      run: MSBuild.exe msvc_test

    - name: vstest.console.exe
      run: |
        & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe' D:\a\snct-constraints\snct-constraints\msvc_test\x64\Release\msvc_test.dll
        
