name: test-action

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: test-job
    runs-on: windows-latest

    steps:
    - name: step-checkout
      uses: actions/checkout@v4.1.7

    - name: step-setup-dependencies
      uses: microsoft/setup-msbuild@v2

    - name: step-build
      run: MSBuild.exe msvc_test

    - name: step-test
      working-directory: D:\a\snct-constraints\snct-constraints\msvc_test\x64\Release
      run: vstest.console.exe msvc_test.dll
